import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ConversationState(str, Enum):
    """Explicit lifecycle state of the AI conversation turn orchestrator."""
    LISTENING = "LISTENING"          # Awaiting audio from caller
    TRANSCRIBING = "TRANSCRIBING"    # STT processing partial/final speech
    THINKING = "THINKING"            # LLM reasoning and generating response
    SPEAKING = "SPEAKING"            # TTS playing outbound speech to caller
    INTERRUPTED = "INTERRUPTED"      # Caller barged in while agent spoke
    ENDING = "ENDING"                # Conversation closing
    ERROR = "ERROR"                  # Recoverable or non-recoverable error


class TurnSpeaker(str, Enum):
    CALLER = "caller"
    AGENT = "agent"
    SYSTEM = "system"


class Utterance(BaseModel):
    utterance_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    speaker: TurnSpeaker
    text: str
    language: str
    confidence: float = 1.0
    is_final: bool = True
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class TranscriptEvent(BaseModel):
    session_id: str
    call_id: str
    speaker: str = "caller"
    text: str
    confidence: float = 0.95
    is_final: bool
    language: str
    start_time_ms: int = 0
    end_time_ms: int = 0

    def __getitem__(self, item: str):
        return getattr(self, item)


class ConversationalResponse(BaseModel):
    """Structured machine-readable output generated by Gemini reasoning layer."""
    response_text: str = Field(..., description="Short 1-2 sentence spoken response for the caller.")
    detected_intent: str = Field(default="GENERAL_INQUIRY", description="Categorized user intent.")
    conversation_state: str = Field(default="ENGAGED", description="High-level dialogue progression state.")
    next_action: str = Field(default="CONTINUE", description="CONTINUE | CLARIFY | SAFETY_HOOK | END_CALL")
    language: str = Field(default="en-IN", description="Language code used for response.")
    confidence: float = Field(default=0.9, description="Confidence score from 0.0 to 1.0.")
    safety_flag: bool = Field(default=False, description="True if caller expressed imminent threat or self-harm.")


class TurnLatency(BaseModel):
    caller_speech_ended_at: Optional[float] = None
    final_transcript_at: Optional[float] = None
    llm_response_at: Optional[float] = None
    first_tts_frame_at: Optional[float] = None

    @property
    def stt_latency_ms(self) -> Optional[int]:
        if self.caller_speech_ended_at and self.final_transcript_at:
            return max(0, int((self.final_transcript_at - self.caller_speech_ended_at) * 1000))
        return None

    @property
    def llm_latency_ms(self) -> Optional[int]:
        if self.final_transcript_at and self.llm_response_at:
            return max(0, int((self.llm_response_at - self.final_transcript_at) * 1000))
        return None

    @property
    def tts_latency_ms(self) -> Optional[int]:
        if self.llm_response_at and self.first_tts_frame_at:
            return max(0, int((self.first_tts_frame_at - self.llm_response_at) * 1000))
        return None

    @property
    def total_turn_latency_ms(self) -> Optional[int]:
        if self.caller_speech_ended_at and self.first_tts_frame_at:
            return max(0, int((self.first_tts_frame_at - self.caller_speech_ended_at) * 1000))
        return None


class SimulatedConversationRequest(BaseModel):
    scenario: str = Field(
        default="tamil_help",
        description="Scenario: 'tamil_help', 'hindi_help', 'english_help', 'code_switch', 'interruption'"
    )
    caller_number: str = "+919876543210"